### ISSUE TITLE
Cozy Meter Visualization

### ISSUE THREAD

**Issue by LemurDev** [LemurDev/CozyBot#5]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Some sort of visualiazation of the cozyness of the stream. Also, when it gets to 100% an event would happen.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by LemurDev** [comment]
Any idea of what should happen when someone get 100%? We could put it in chat that someone got 100% but should something pop up on the screen maybe?

**Comment by LemurDev** [comment]
Added the following code to my remote copy. When someone gets 100%, it will say it in chat. Not going to push the changes yet since not sure what else should happen.

```python
        if int(cozyness) > int(self.old_cozyness):
            with open("cozy.txt", "w") as file:
                file.write(f"{user}-{cozyness}%")
                file.close()
            self.old_cozyness = cozyness
            if int(cozyness) == 100:
                await ctx.send(f"@{ctx.author.name} has reached 100% cozyness!")
```

**Comment by LemurDev** [comment]
@williamrhayes https://github.com/LemurDev/CozyBot/tree/dev

Tried to start the building blocks for an event. Pushed it to dev just to see what you think. To see it in action, create another streamlabel for `100_cozy.txt` Doesn't look the best but we can improve on it if need be.

**Comment by williamrhayes** [comment]
I like it, only thing I would change is removing 

`file.close()` 

at the end of the `with `statement. When you use `with`, the open and close commands are taken care of for you.

**Comment by LemurDev** [comment]
Will do! Is the event good enough? Or should it be worked on more?

**Comment by williamrhayes** [comment]
Yup, the event itself is fine. It leaves us the space to add additional features later if we decide we want to make 100% cozy into a bigger event.

**Comment by LemurDev** [comment]
Just did some testing. When I removed `file.close` the `100_cozy.txt` file did not have its contents removed.
